// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: chatMsg/msg.proto

package chatMsg

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MsgContentType int32

const (
	MsgContentType_MsgContentTypeErr MsgContentType = 0
	MsgContentType_Text              MsgContentType = 1
	MsgContentType_Img               MsgContentType = 2
	MsgContentType_Video             MsgContentType = 3
)

// Enum value maps for MsgContentType.
var (
	MsgContentType_name = map[int32]string{
		0: "MsgContentTypeErr",
		1: "Text",
		2: "Img",
		3: "Video",
	}
	MsgContentType_value = map[string]int32{
		"MsgContentTypeErr": 0,
		"Text":              1,
		"Img":               2,
		"Video":             3,
	}
)

func (x MsgContentType) Enum() *MsgContentType {
	p := new(MsgContentType)
	*p = x
	return p
}

func (x MsgContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_chatMsg_msg_proto_enumTypes[0].Descriptor()
}

func (MsgContentType) Type() protoreflect.EnumType {
	return &file_chatMsg_msg_proto_enumTypes[0]
}

func (x MsgContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgContentType.Descriptor instead.
func (MsgContentType) EnumDescriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{0}
}

type MsgType int32

const (
	MsgType_MsgTypeErr MsgType = 0
	MsgType_Single     MsgType = 1
	MsgType_Group      MsgType = 2
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MsgTypeErr",
		1: "Single",
		2: "Group",
	}
	MsgType_value = map[string]int32{
		"MsgTypeErr": 0,
		"Single":     1,
		"Group":      2,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_chatMsg_msg_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_chatMsg_msg_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{1}
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Md5 string `protobuf:"bytes,1,opt,name=md5,proto3" json:"md5,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatMsg_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_chatMsg_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Ack) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From           string         `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Target         string         `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Content        []byte         `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MsgType        MsgType        `protobuf:"varint,4,opt,name=msgType,proto3,enum=chatMsg.MsgType" json:"msgType,omitempty"`
	MsgContentType MsgContentType `protobuf:"varint,5,opt,name=msgContentType,proto3,enum=chatMsg.MsgContentType" json:"msgContentType,omitempty"`
	SendTime       string         `protobuf:"bytes,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	// group chat usage.
	GroupName string `protobuf:"bytes,7,opt,name=groupName,proto3" json:"groupName,omitempty"`
	Spread    bool   `protobuf:"varint,8,opt,name=spread,proto3" json:"spread,omitempty"`
	// msgId
	MsgId string `protobuf:"bytes,30,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatMsg_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_chatMsg_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{1}
}

func (x *Msg) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Msg) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Msg) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Msg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MsgTypeErr
}

func (x *Msg) GetMsgContentType() MsgContentType {
	if x != nil {
		return x.MsgContentType
	}
	return MsgContentType_MsgContentTypeErr
}

func (x *Msg) GetSendTime() string {
	if x != nil {
		return x.SendTime
	}
	return ""
}

func (x *Msg) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Msg) GetSpread() bool {
	if x != nil {
		return x.Spread
	}
	return false
}

func (x *Msg) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

type MsgPack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgList []*Msg `protobuf:"bytes,1,rep,name=msgList,proto3" json:"msgList,omitempty"`
}

func (x *MsgPack) Reset() {
	*x = MsgPack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatMsg_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPack) ProtoMessage() {}

func (x *MsgPack) ProtoReflect() protoreflect.Message {
	mi := &file_chatMsg_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPack.ProtoReflect.Descriptor instead.
func (*MsgPack) Descriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MsgPack) GetMsgList() []*Msg {
	if x != nil {
		return x.MsgList
	}
	return nil
}

type PullReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
}

func (x *PullReq) Reset() {
	*x = PullReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatMsg_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullReq) ProtoMessage() {}

func (x *PullReq) ProtoReflect() protoreflect.Message {
	mi := &file_chatMsg_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullReq.ProtoReflect.Descriptor instead.
func (*PullReq) Descriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{3}
}

func (x *PullReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type KeepAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CheckAlive  string   `protobuf:"bytes,1,opt,name=checkAlive,proto3" json:"checkAlive,omitempty"`
	Errors      []string `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	MsgRecv     int32    `protobuf:"varint,6,opt,name=msgRecv,proto3" json:"msgRecv,omitempty"`
	MsgSend     int32    `protobuf:"varint,7,opt,name=msgSend,proto3" json:"msgSend,omitempty"`
	MsgNotLocal int32    `protobuf:"varint,8,opt,name=msgNotLocal,proto3" json:"msgNotLocal,omitempty"`
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatMsg_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_chatMsg_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{4}
}

func (x *KeepAlive) GetCheckAlive() string {
	if x != nil {
		return x.CheckAlive
	}
	return ""
}

func (x *KeepAlive) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *KeepAlive) GetMsgRecv() int32 {
	if x != nil {
		return x.MsgRecv
	}
	return 0
}

func (x *KeepAlive) GetMsgSend() int32 {
	if x != nil {
		return x.MsgSend
	}
	return 0
}

func (x *KeepAlive) GetMsgNotLocal() int32 {
	if x != nil {
		return x.MsgNotLocal
	}
	return 0
}

type GroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	GroupName string `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	IsCopy    bool   `protobuf:"varint,3,opt,name=isCopy,proto3" json:"isCopy,omitempty"`
}

func (x *GroupReq) Reset() {
	*x = GroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatMsg_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReq) ProtoMessage() {}

func (x *GroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_chatMsg_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReq.ProtoReflect.Descriptor instead.
func (*GroupReq) Descriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{5}
}

func (x *GroupReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *GroupReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupReq) GetIsCopy() bool {
	if x != nil {
		return x.IsCopy
	}
	return false
}

type GroupRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GroupRsp) Reset() {
	*x = GroupRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatMsg_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRsp) ProtoMessage() {}

func (x *GroupRsp) ProtoReflect() protoreflect.Message {
	mi := &file_chatMsg_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRsp.ProtoReflect.Descriptor instead.
func (*GroupRsp) Descriptor() ([]byte, []int) {
	return file_chatMsg_msg_proto_rawDescGZIP(), []int{6}
}

func (x *GroupRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_chatMsg_msg_proto protoreflect.FileDescriptor

var file_chatMsg_msg_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x22, 0x17, 0x0a, 0x03,
	0x41, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x64, 0x35, 0x22, 0xa0, 0x02, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x3f, 0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73,
	0x67, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0e, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70,
	0x72, 0x65, 0x61, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x70, 0x72, 0x65,
	0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x1e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x50,
	0x61, 0x63, 0x6b, 0x12, 0x26, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4d,
	0x73, 0x67, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x07, 0x50,
	0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x22, 0x99, 0x01, 0x0a, 0x09, 0x4b,
	0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x76, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73,
	0x67, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73, 0x67,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x4e, 0x6f, 0x74, 0x4c, 0x6f,
	0x63, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x73, 0x67, 0x4e, 0x6f,
	0x74, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x22, 0x52, 0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x43, 0x6f, 0x70, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x43, 0x6f, 0x70, 0x79, 0x22, 0x1c, 0x0a, 0x08, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x45, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x4d, 0x73,
	0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x45, 0x72, 0x72, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x49,
	0x6d, 0x67, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x03, 0x2a,
	0x30, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x73,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x45, 0x72, 0x72, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x10,
	0x02, 0x32, 0xd0, 0x03, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x43, 0x79, 0x6e, 0x69, 0x63, 0x12, 0x24,
	0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x12, 0x0c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d,
	0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x1a, 0x0c, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67,
	0x2e, 0x41, 0x63, 0x6b, 0x12, 0x2a, 0x0a, 0x04, 0x50, 0x75, 0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x61, 0x63, 0x6b,
	0x12, 0x2d, 0x0a, 0x07, 0x50, 0x75, 0x6c, 0x6c, 0x41, 0x6c, 0x6c, 0x12, 0x10, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x61, 0x63, 0x6b, 0x12,
	0x34, 0x0a, 0x0a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x12, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76,
	0x65, 0x1a, 0x12, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4b, 0x65, 0x65, 0x70,
	0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x3c, 0x0a, 0x12, 0x53, 0x79, 0x6e, 0x63, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x12, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x1a,
	0x12, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x12, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73,
	0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x73, 0x70, 0x12,
	0x33, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x11,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x73, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatMsg_msg_proto_rawDescOnce sync.Once
	file_chatMsg_msg_proto_rawDescData = file_chatMsg_msg_proto_rawDesc
)

func file_chatMsg_msg_proto_rawDescGZIP() []byte {
	file_chatMsg_msg_proto_rawDescOnce.Do(func() {
		file_chatMsg_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatMsg_msg_proto_rawDescData)
	})
	return file_chatMsg_msg_proto_rawDescData
}

var file_chatMsg_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatMsg_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chatMsg_msg_proto_goTypes = []interface{}{
	(MsgContentType)(0), // 0: chatMsg.MsgContentType
	(MsgType)(0),        // 1: chatMsg.MsgType
	(*Ack)(nil),         // 2: chatMsg.Ack
	(*Msg)(nil),         // 3: chatMsg.Msg
	(*MsgPack)(nil),     // 4: chatMsg.MsgPack
	(*PullReq)(nil),     // 5: chatMsg.PullReq
	(*KeepAlive)(nil),   // 6: chatMsg.KeepAlive
	(*GroupReq)(nil),    // 7: chatMsg.GroupReq
	(*GroupRsp)(nil),    // 8: chatMsg.GroupRsp
}
var file_chatMsg_msg_proto_depIdxs = []int32{
	1,  // 0: chatMsg.Msg.msgType:type_name -> chatMsg.MsgType
	0,  // 1: chatMsg.Msg.msgContentType:type_name -> chatMsg.MsgContentType
	3,  // 2: chatMsg.MsgPack.msgList:type_name -> chatMsg.Msg
	3,  // 3: chatMsg.MsgCynic.SendTo:input_type -> chatMsg.Msg
	5,  // 4: chatMsg.MsgCynic.Pull:input_type -> chatMsg.PullReq
	5,  // 5: chatMsg.MsgCynic.PullAll:input_type -> chatMsg.PullReq
	6,  // 6: chatMsg.MsgCynic.CheckAlive:input_type -> chatMsg.KeepAlive
	6,  // 7: chatMsg.MsgCynic.SyncLocationNotify:input_type -> chatMsg.KeepAlive
	7,  // 8: chatMsg.MsgCynic.JoinGroup:input_type -> chatMsg.GroupReq
	7,  // 9: chatMsg.MsgCynic.LeaveGroup:input_type -> chatMsg.GroupReq
	7,  // 10: chatMsg.MsgCynic.CreateGroup:input_type -> chatMsg.GroupReq
	7,  // 11: chatMsg.MsgCynic.DeleteGroup:input_type -> chatMsg.GroupReq
	2,  // 12: chatMsg.MsgCynic.SendTo:output_type -> chatMsg.Ack
	4,  // 13: chatMsg.MsgCynic.Pull:output_type -> chatMsg.MsgPack
	4,  // 14: chatMsg.MsgCynic.PullAll:output_type -> chatMsg.MsgPack
	6,  // 15: chatMsg.MsgCynic.CheckAlive:output_type -> chatMsg.KeepAlive
	6,  // 16: chatMsg.MsgCynic.SyncLocationNotify:output_type -> chatMsg.KeepAlive
	8,  // 17: chatMsg.MsgCynic.JoinGroup:output_type -> chatMsg.GroupRsp
	8,  // 18: chatMsg.MsgCynic.LeaveGroup:output_type -> chatMsg.GroupRsp
	8,  // 19: chatMsg.MsgCynic.CreateGroup:output_type -> chatMsg.GroupRsp
	8,  // 20: chatMsg.MsgCynic.DeleteGroup:output_type -> chatMsg.GroupRsp
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chatMsg_msg_proto_init() }
func file_chatMsg_msg_proto_init() {
	if File_chatMsg_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatMsg_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatMsg_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatMsg_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatMsg_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatMsg_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeepAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatMsg_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatMsg_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatMsg_msg_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatMsg_msg_proto_goTypes,
		DependencyIndexes: file_chatMsg_msg_proto_depIdxs,
		EnumInfos:         file_chatMsg_msg_proto_enumTypes,
		MessageInfos:      file_chatMsg_msg_proto_msgTypes,
	}.Build()
	File_chatMsg_msg_proto = out.File
	file_chatMsg_msg_proto_rawDesc = nil
	file_chatMsg_msg_proto_goTypes = nil
	file_chatMsg_msg_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MsgCynicClient is the client API for MsgCynic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgCynicClient interface {
	// Send Msg To Server
	SendTo(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Ack, error)
	// pull myself message from Server
	Pull(ctx context.Context, in *PullReq, opts ...grpc.CallOption) (*MsgPack, error)
	// pull all message from cluster
	PullAll(ctx context.Context, in *PullReq, opts ...grpc.CallOption) (*MsgPack, error)
	// check if this Keeper is alive or not
	CheckAlive(ctx context.Context, in *KeepAlive, opts ...grpc.CallOption) (*KeepAlive, error)
	// notify keeper to sync cluster message
	SyncLocationNotify(ctx context.Context, in *KeepAlive, opts ...grpc.CallOption) (*KeepAlive, error)
	// join into a group
	JoinGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error)
	// Leave from a group
	LeaveGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error)
	// Create a group
	CreateGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error)
	// Delete a group
	DeleteGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error)
}

type msgCynicClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgCynicClient(cc grpc.ClientConnInterface) MsgCynicClient {
	return &msgCynicClient{cc}
}

func (c *msgCynicClient) SendTo(ctx context.Context, in *Msg, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/SendTo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) Pull(ctx context.Context, in *PullReq, opts ...grpc.CallOption) (*MsgPack, error) {
	out := new(MsgPack)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/Pull", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) PullAll(ctx context.Context, in *PullReq, opts ...grpc.CallOption) (*MsgPack, error) {
	out := new(MsgPack)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/PullAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) CheckAlive(ctx context.Context, in *KeepAlive, opts ...grpc.CallOption) (*KeepAlive, error) {
	out := new(KeepAlive)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/CheckAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) SyncLocationNotify(ctx context.Context, in *KeepAlive, opts ...grpc.CallOption) (*KeepAlive, error) {
	out := new(KeepAlive)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/SyncLocationNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) JoinGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error) {
	out := new(GroupRsp)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/JoinGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) LeaveGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error) {
	out := new(GroupRsp)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/LeaveGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) CreateGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error) {
	out := new(GroupRsp)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgCynicClient) DeleteGroup(ctx context.Context, in *GroupReq, opts ...grpc.CallOption) (*GroupRsp, error) {
	out := new(GroupRsp)
	err := c.cc.Invoke(ctx, "/chatMsg.MsgCynic/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgCynicServer is the server API for MsgCynic service.
type MsgCynicServer interface {
	// Send Msg To Server
	SendTo(context.Context, *Msg) (*Ack, error)
	// pull myself message from Server
	Pull(context.Context, *PullReq) (*MsgPack, error)
	// pull all message from cluster
	PullAll(context.Context, *PullReq) (*MsgPack, error)
	// check if this Keeper is alive or not
	CheckAlive(context.Context, *KeepAlive) (*KeepAlive, error)
	// notify keeper to sync cluster message
	SyncLocationNotify(context.Context, *KeepAlive) (*KeepAlive, error)
	// join into a group
	JoinGroup(context.Context, *GroupReq) (*GroupRsp, error)
	// Leave from a group
	LeaveGroup(context.Context, *GroupReq) (*GroupRsp, error)
	// Create a group
	CreateGroup(context.Context, *GroupReq) (*GroupRsp, error)
	// Delete a group
	DeleteGroup(context.Context, *GroupReq) (*GroupRsp, error)
}

// UnimplementedMsgCynicServer can be embedded to have forward compatible implementations.
type UnimplementedMsgCynicServer struct {
}

func (*UnimplementedMsgCynicServer) SendTo(context.Context, *Msg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTo not implemented")
}
func (*UnimplementedMsgCynicServer) Pull(context.Context, *PullReq) (*MsgPack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (*UnimplementedMsgCynicServer) PullAll(context.Context, *PullReq) (*MsgPack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullAll not implemented")
}
func (*UnimplementedMsgCynicServer) CheckAlive(context.Context, *KeepAlive) (*KeepAlive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAlive not implemented")
}
func (*UnimplementedMsgCynicServer) SyncLocationNotify(context.Context, *KeepAlive) (*KeepAlive, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncLocationNotify not implemented")
}
func (*UnimplementedMsgCynicServer) JoinGroup(context.Context, *GroupReq) (*GroupRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGroup not implemented")
}
func (*UnimplementedMsgCynicServer) LeaveGroup(context.Context, *GroupReq) (*GroupRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (*UnimplementedMsgCynicServer) CreateGroup(context.Context, *GroupReq) (*GroupRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedMsgCynicServer) DeleteGroup(context.Context, *GroupReq) (*GroupRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}

func RegisterMsgCynicServer(s *grpc.Server, srv MsgCynicServer) {
	s.RegisterService(&_MsgCynic_serviceDesc, srv)
}

func _MsgCynic_SendTo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Msg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).SendTo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/SendTo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).SendTo(ctx, req.(*Msg))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).Pull(ctx, req.(*PullReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_PullAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).PullAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/PullAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).PullAll(ctx, req.(*PullReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_CheckAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAlive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).CheckAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/CheckAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).CheckAlive(ctx, req.(*KeepAlive))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_SyncLocationNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAlive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).SyncLocationNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/SyncLocationNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).SyncLocationNotify(ctx, req.(*KeepAlive))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/JoinGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).JoinGroup(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/LeaveGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).LeaveGroup(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).CreateGroup(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgCynic_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgCynicServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatMsg.MsgCynic/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgCynicServer).DeleteGroup(ctx, req.(*GroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgCynic_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatMsg.MsgCynic",
	HandlerType: (*MsgCynicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTo",
			Handler:    _MsgCynic_SendTo_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _MsgCynic_Pull_Handler,
		},
		{
			MethodName: "PullAll",
			Handler:    _MsgCynic_PullAll_Handler,
		},
		{
			MethodName: "CheckAlive",
			Handler:    _MsgCynic_CheckAlive_Handler,
		},
		{
			MethodName: "SyncLocationNotify",
			Handler:    _MsgCynic_SyncLocationNotify_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _MsgCynic_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _MsgCynic_LeaveGroup_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _MsgCynic_CreateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _MsgCynic_DeleteGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatMsg/msg.proto",
}
